### ISSUE TITLE
push the artifact to Maven central

### ISSUE THREAD

**Issue by ludoch** [googleapis/java-docfx-doclet#105]
If the artifact is pushed, we can avoid hardcoded values like that are complicated to managed,

              <docletPath>${env.KOKORO_GFILE_DIR}/${docletName}.jar</docletPath>

and instead use:

               <docletArtifact>
                <groupId>java-docfx-doccheck</groupId>
                <artifactId>doccheck</artifactId>
                <version>1.5.0</version>
              </docletArtifact>

**Comment by ludoch** [comment]
Feel free to pick whatever groupId matching google needs.

**Comment by eaball35** [comment]
I've been thinking about doing this for awhile but never got around to it, now that we're expanding the use of the doclet I think it's worth doing.

**Comment by alicejli** [comment]
Closing this issue as we've migrated the release scripts to g3 and are checking out tagged versions of the doclet for c.g.c. publication. This applies for all libraries published to cloud.google.com. Please reopen if there's a use case I'm missing here.
