### ISSUE TITLE
Cleanup HTML functionality adding in unnecessary H2 tags

### ISSUE THREAD

**Issue by lqiu96** [googleapis/java-docfx-doclet#135]
#### Environment details

  - Programming language: Java
  - OS: Linux
  - Language runtime version: Java 11
  - Package version: v1.6.0

#### Steps to reproduce

Tha YAMLUtil.cleanupHTML function is replacing the `==` blocks with h2 tags: 
https://github.com/googleapis/java-docfx-doclet/blob/main/third_party/docfx-doclet-143274/src/main/java/com/microsoft/util/YamlUtil.java#L38

This is causing errors in the EnvironmentsClient.java file in java-orchestration-airflow: 
https://github.com/googleapis/java-orchestration-airflow/blob/main/google-cloud-orchestration-airflow/src/main/java/com/google/cloud/orchestration/airflow/service/v1/EnvironmentsClient.java#L525-L542

`
This replaces "scikit-learn":"==0.19.0" to "scikit-learn":"<h2>0.19.0" and "botocore":"==1.7.14" to "botocore":"</h2>1.7.14"
`

The added h2 tags is invalid HTML and the javadoc is throwing errors.

**Comment by eaball35** [comment]
Yes, this is the correct assumption. Test it out, but your possible replacement should work. There was originally a bug filed awhile back about the way these headers appeared in ref docs like this so I just parsed it out. Ideally we could move some of this cleanup logic to the original generation in gapic generator.
