### ISSUE TITLE
BigQuery Unicode Javadoc not rendering correctly

### ISSUE THREAD

**Issue by lqiu96** [googleapis/java-docfx-doclet#161]
Issue:
![image](https://user-images.githubusercontent.com/6621793/200620098-6582bb80-53bf-4ede-bdd1-3fb1d869e2b7.png)

at https://cloud.google.com/java/docs/reference/google-cloud-bigquery/latest/com.google.cloud.bigquery.Field.Builder#com_google_cloud_bigquery_Field_Builder_setPrecision_java_lang_Long_

Should render: 
![image](https://user-images.githubusercontent.com/6621793/200620014-7fb62b2a-877f-4544-8ee7-ca8e7e8673ef.png)

This change should have this in the `.yml` files:
```
summary: "Precision can be used to constrain the maximum number of total digits allowed for NUMERIC or\n BIGNUMERIC types. It is invalid to set values for Precision for types other than // NUMERIC\n or BIGNUMERIC. For NUMERIC type, acceptable values for Precision must be: 1 ≤ (Precision -\n Scale) ≤ 29. Values for Scale must be: 0 ≤ Scale ≤ 9. For BIGNUMERIC type, acceptable values\n for Precision must be: 1 ≤ (Precision - Scale) ≤ 38. Values for Scale must be: 0 ≤ Scale ≤\n 38."
```

**Comment by suztomo** [comment]
You write a nice summary of the issue.
